### ISSUE TITLE
Navigating views

### ISSUE THREAD

**Issue by drhitchcockco** [Nanobot567/CS-16#2]
When cycling through options using the crank users might find it useful if there was some representation of what number option they were in out of how many. For example if one was cycling through the screen option the label displayed might be:
* "Screen :: Pattern :: 1 / 3"
* "Screen :: Track :: 2 / 3"
* "Screen :: Song :: 3 / 3"

The same with cycling through the button "B" options. For example on the pattern screen:
* "Pattern :: Note status :: 1 / 6"
* "Pattern :: Pitch :: 2 / 6"
* "Pattern :: Length :: 3 / 6"
* "Pattern :: Velocity :: 4 / 6"
* "Pattern :: Track :: 5 / 6"
* "Pattern :: Screen :: 6 / 6"

I appreciate it might get a little messy but it might be helpful in indicating to the user where they are in the flow of the program and take some of the mental load off of having to remember where they are and what menu option is next.

**Comment by Nanobot567** [comment]
Yeah, I can see it getting pretty tiring to keep track of all of the options... Unfortunately I'm going to be away from my computer for a week or so, so I can't implement it right away. Sorry to keep you waiting, but I'll add it in as soon as I can!

Thanks!

**Comment by Nanobot567** [comment]
Okay, I've added this to CS-16! The format is `(option text) - number/maximum`, and I've also included a settings option to turn this off. Does that seem alright?

**Comment by drhitchcockco** [comment]
This is amazing! Exactly what I had in mind. Thanks for the swift turn around. You're a true Tech Lorde!! How do I go about trying it out? I've cloned the main branch. Also, how do I flick you some cash 😊

**Comment by Nanobot567** [comment]
Oh I haven't actually committed it to main yet, give me a moment and I will :)

Also I'm not currently accepting donations (I'm trying not to be that guy who's shoving their Patreon down other people's throats lol), if I end up setting one up though I'll let you know. Thanks anyways!

**Comment by Nanobot567** [comment]
Annnnnnd it's done!! The new .pdx should be in the releases tab.

**Comment by drhitchcockco** [comment]
Thanks again! It's ok to be that cat. Everyone's gotta pay the stupid bills 🫠
